import getPostcode from './requests'

const dealers = [{
        "Site ID": "26",
        "Base Code": "41412",
        "Main / Car Dealer Code": "41412AA",
        "CV Dealer Code": "41413AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London",
        "Address1": "319 The Hyde",
        "Address2": "Edgware Road",
        "Address3": "London",
        "Address4": "",
        "Post Code": "NW9 6TH",
        "Phone Number": "020 8358 8600",
        "Fax Number": "020 8358 8601",
        "CMA Number": "17",
        "CMA Description": "N London",
        "Group Name": "Ford Retail",
        "eastings": "520776",
        "northings": "189388"
    },
    {
        "Site ID": "26",
        "Base Code": "41412",
        "Main / Car Dealer Code": "97614AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford (Fleet Admin)",
        "Location": "London",
        "Address1": "319 The Hyde",
        "Address2": "Edgware Road",
        "Address3": "London",
        "Address4": "",
        "Post Code": "NW9 6TH",
        "Phone Number": "020 8358 8600",
        "Fax Number": "020 8358 8601",
        "CMA Number": "17",
        "CMA Description": "N London",
        "Group Name": "Ford Retail",
        "eastings": "520776",
        "northings": "189388"
    },
    {
        "Site ID": "23",
        "Base Code": "42229",
        "Main / Car Dealer Code": "42229AA",
        "CV Dealer Code": "43814BA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Staines)",
        "Address1": "268 London Road",
        "Address2": "Staines",
        "Address3": "Greater London",
        "Address4": "",
        "Post Code": "TW18 4JQ",
        "Phone Number": "01784 466 666",
        "Fax Number": "01932 332 910",
        "CMA Number": "32",
        "CMA Description": "W London",
        "Group Name": "Ford Retail",
        "eastings": "504767",
        "northings": "172047"
    },
    {
        "Site ID": "1400",
        "Base Code": "42386",
        "Main / Car Dealer Code": "",
        "CV Dealer Code": "97726AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Dagenham CV BC (FLEET ADMIN)",
        "Location": "Dagenham",
        "Address1": "Unit 3 Orion Park",
        "Address2": "Dagenham",
        "Address3": "Essex",
        "Address4": "",
        "Post Code": "RM9 6FF",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "10",
        "CMA Description": "NE London",
        "Group Name": "Ford Retail",
        "eastings": "548750",
        "northings": "183200"
    },
    {
        "Site ID": "254",
        "Base Code": "42386",
        "Main / Car Dealer Code": "42386AA",
        "CV Dealer Code": "42413AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Barking)",
        "Address1": "Ripple Road",
        "Address2": "Barking",
        "Address3": "Essex",
        "Address4": "",
        "Post Code": "IG11 9PG",
        "Phone Number": "020 8911 3333",
        "Fax Number": "020 8591 9380",
        "CMA Number": "10",
        "CMA Description": "NE London",
        "Group Name": "Ford Retail",
        "eastings": "546140",
        "northings": "183713"
    },
    {
        "Site ID": "1219",
        "Base Code": "42386",
        "Main / Car Dealer Code": "42386IA",
        "CV Dealer Code": "42413IA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Dagenham)",
        "Address1": "Unit 3, Orion Park",
        "Address2": "Messina Way",
        "Address3": "Dagenham",
        "Address4": "Essex",
        "Post Code": "RM9 6FF",
        "Phone Number": "0343  308 3954",
        "Fax Number": "tba",
        "CMA Number": "10",
        "CMA Description": "NE London",
        "Group Name": "Ford Retail",
        "eastings": "548750",
        "northings": "183200"
    },
    {
        "Site ID": "1401",
        "Base Code": "42386",
        "Main / Car Dealer Code": "97725AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Dagenham Car BC (FLEET ADMIN)",
        "Location": "Dagenham",
        "Address1": "Ripple Road",
        "Address2": "Barking",
        "Address3": "Essex",
        "Address4": "",
        "Post Code": "IG11 9PG",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "10",
        "CMA Description": "NE London",
        "Group Name": "Ford Retail",
        "eastings": "546140",
        "northings": "183713"
    },
    {
        "Site ID": "1160",
        "Base Code": "42386",
        "Main / Car Dealer Code": "98589AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust First Parts",
        "Location": "Thurrock",
        "Address1": "Unit B, The Triton Centre",
        "Address2": "Weston Avenue",
        "Address3": "Waterglade Industrial Park",
        "Address4": "West Thurrock, Grays, Essex",
        "Post Code": "RM20 3FN",
        "Phone Number": "01708 893900",
        "Fax Number": "01708 893919",
        "CMA Number": "10",
        "CMA Description": "NE London",
        "Group Name": "Ford Retail",
        "eastings": "557567",
        "northings": "178193"
    },
    {
        "Site ID": "1144",
        "Base Code": "43814",
        "CV Dealer Code": "43814AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Hayes)",
        "Address1": "Unit 37, Fairview Industrial Estate",
        "Address2": "Clayton Road",
        "Address3": "Hayes",
        "Address4": "Middlesex",
        "Post Code": "UB3 1AN",
        "Phone Number": "020 8561 8888",
        "Fax Number": "020 8606 1511",
        "CMA Number": "36",
        "CMA Description": "Uxbridge",
        "Group Name": "Ford Retail",
        "eastings": "509617",
        "northings": "179634"
    },
    {
        "Site ID": "29",
        "Base Code": "44401",
        "Main / Car Dealer Code": "44401AA",
        "CV Dealer Code": "43814FA",
        "Additional FCSD Dealer Code": "98583AA",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Alperton)",
        "Address1": "374 Ealing Road",
        "Address2": "Alperton",
        "Address3": "Wembley",
        "Address4": "Greater London",
        "Post Code": "HA0 1HG",
        "Phone Number": "020 8810 2600",
        "Fax Number": "020 8991 5245",
        "CMA Number": "1",
        "CMA Description": "NW London",
        "Group Name": "Ford Retail",
        "eastings": "518004",
        "northings": "183365"
    },
    {
        "Site ID": "1022",
        "Base Code": "44847",
        "Main / Car Dealer Code": "44847AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "London (Eltham)",
        "Address1": "701-725 Sidcup Road",
        "Address2": "Eltham",
        "Address3": "London",
        "Address4": "",
        "Post Code": "SE9 3AQ",
        "Phone Number": "020 8860 1266",
        "Fax Number": "020 8860 1277",
        "CMA Number": "3",
        "CMA Description": "Bexley, Dartford, Gravesend",
        "Group Name": "Ford Retail",
        "eastings": "543328",
        "northings": "172826"
    },
    {
        "Site ID": "13",
        "Base Code": "46101",
        "Main / Car Dealer Code": "46101AA",
        "CV Dealer Code": "46487AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Gillingham",
        "Address1": "161-169 Pier Road",
        "Address2": "Gillingham",
        "Address3": "Kent",
        "Address4": "",
        "Post Code": "ME7 1AF",
        "Phone Number": "01634 280 111",
        "Fax Number": "01634 280 870",
        "CMA Number": "64",
        "CMA Description": "Medway/Maidstone",
        "Group Name": "Ford Retail",
        "eastings": "577898",
        "northings": "169479"
    },
    {
        "Site ID": "264",
        "Base Code": "46101",
        "Main / Car Dealer Code": "46101BA",
        "CV Dealer Code": "46487BA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Strood",
        "Address1": "Unit 1, Ballard Business Park",
        "Address2": "Cuxton Road",
        "Address3": "Strood",
        "Address4": "Kent",
        "Post Code": "ME2 2NY",
        "Phone Number": "01634 496 300",
        "Fax Number": "01634 721 324",
        "CMA Number": "64",
        "CMA Description": "Medway/Maidstone",
        "Group Name": "Ford Retail",
        "eastings": "572690",
        "northings": "168060"
    },
    {
        "Site ID": "151",
        "Base Code": "48488",
        "Main / Car Dealer Code": "48488AA",
        "CV Dealer Code": "48489AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Byfleet",
        "Address1": "Wintersells Road",
        "Address2": "Byfleet",
        "Address3": "Surrey",
        "Address4": "",
        "Post Code": "KT14 7LF",
        "Phone Number": "01932 332900",
        "Fax Number": "01932 332910",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "506019",
        "northings": "162257"
    },
    {
        "Site ID": "275",
        "Base Code": "48488",
        "Main / Car Dealer Code": "48488CA",
        "CV Dealer Code": "48489CA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Cobham",
        "Address1": "97 Portsmouth Road",
        "Address2": "Cobham",
        "Address3": "Surrey",
        "Address4": "",
        "Post Code": "KT11 1JJ",
        "Phone Number": "01932 588500",
        "Fax Number": "01932 866326",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "510617",
        "northings": "160599"
    },
    {
        "Site ID": "1222",
        "Base Code": "48488",
        "Main / Car Dealer Code": "48488EA",
        "CV Dealer Code": "48489EA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Epsom",
        "Address1": "Blenheim Road",
        "Address2": "Longmead Industrial Estate",
        "Address3": "Epsom",
        "Address4": "Surrey",
        "Post Code": "KT19 9NW",
        "Phone Number": "01372 804000",
        "Fax Number": "01372 804001",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "520990",
        "northings": "161641"
    },
    {
        "Site ID": "391",
        "Base Code": "48488",
        "Main / Car Dealer Code": "48488GA",
        "CV Dealer Code": "48489GA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Banstead",
        "Address1": "A217 Brighton Road",
        "Address2": "Banstead",
        "Address3": "Surrey",
        "Address4": "",
        "Post Code": "SM7 1BS",
        "Phone Number": "03448 580109",
        "Fax Number": "01737 360517",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "524711",
        "northings": "159295"
    },
    {
        "Site ID": "338",
        "Base Code": "48488",
        "Main / Car Dealer Code": "48488IA",
        "CV Dealer Code": "48489IA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Thames Ditton",
        "Address1": "Brook House",
        "Address2": "Portsmouth Road",
        "Address3": "Thames Ditton",
        "Address4": "",
        "Post Code": "KT7 0EG",
        "Phone Number": "0208 339 3500",
        "Fax Number": "020 8339 3503",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "516303",
        "northings": "166579"
    },
    {
        "Site ID": "1399",
        "Base Code": "48488",
        "Main / Car Dealer Code": "97721AA",
        "CV Dealer Code": "97722AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Epsom BC (FLEET ADMIN)",
        "Location": "Epsom",
        "Address1": "Blenheim Road",
        "Address2": "Longmead Ind Estate",
        "Address3": "Epsom",
        "Address4": "Surrey",
        "Post Code": "KT19 9NW",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "520990",
        "northings": "161641"
    },
    {
        "Site ID": "1213",
        "Base Code": "48488",
        "Main / Car Dealer Code": "98585AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust First Parts",
        "Location": "Epsom",
        "Address1": "Unit A2, Longmead Business Centre",
        "Address2": "Blenheim Road",
        "Address3": "Epsom",
        "Address4": "Surrey",
        "Post Code": "KT19 9QQ",
        "Phone Number": "01372 877555",
        "Fax Number": "01372 877556",
        "CMA Number": "126",
        "CMA Description": "S W London",
        "Group Name": "Ford Retail",
        "eastings": "520941",
        "northings": "161666"
    },
    {
        "Site ID": "44",
        "Base Code": "62133",
        "Main / Car Dealer Code": "62133AA",
        "CV Dealer Code": "62134AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Wilmslow",
        "Address1": "A34 By Pass",
        "Address2": "Wilmslow",
        "Address3": "Cheshire",
        "Address4": "",
        "Post Code": "SK9 1AE",
        "Phone Number": "01625 257777",
        "Fax Number": "01625 258888",
        "CMA Number": "99",
        "CMA Description": "Stockport",
        "Group Name": "Ford Retail",
        "eastings": "385117",
        "northings": "381238"
    },
    {
        "Site ID": "357",
        "Base Code": "62133",
        "Main / Car Dealer Code": "62133DA",
        "CV Dealer Code": "62134DA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Stockport",
        "Address1": "Wellington Road North",
        "Address2": "Stockport",
        "Address3": "Cheshire",
        "Address4": "",
        "Post Code": "SK4 2PD",
        "Phone Number": "0161 975 5522",
        "Fax Number": "0161 431 5275",
        "CMA Number": "99",
        "CMA Description": "Stockport",
        "Group Name": "Ford Retail",
        "eastings": "388608",
        "northings": "391394"
    },
    {
        "Site ID": "1403",
        "Base Code": "62133",
        "Main / Car Dealer Code": "97708AA",
        "CV Dealer Code": "97709AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford Stockport BC (FLEET ADMIN)",
        "Location": "Stockport",
        "Address1": "Wellington Road North",
        "Address2": "Stockport",
        "Address3": "Cheshire",
        "Address4": "",
        "Post Code": "SK4 2PD",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "99",
        "CMA Description": "Stockport",
        "Group Name": "Ford Retail",
        "eastings": "388608",
        "northings": "391394"
    },
    {
        "Site ID": "1206",
        "Base Code": "62133",
        "Main / Car Dealer Code": "98592AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust First Parts",
        "Location": "Warrington",
        "Address1": "19 Kingsland Grange",
        "Address2": "Woolston",
        "Address3": "Warrington",
        "Address4": "Cheshire",
        "Post Code": "WA1 4RW",
        "Phone Number": "01925 900900",
        "Fax Number": "01925 963777",
        "CMA Number": "99",
        "CMA Description": "Stockport",
        "Group Name": "Ford Retail",
        "eastings": "364530",
        "northings": "390260"
    },
    {
        "Site ID": "127",
        "Base Code": "63360",
        "Main / Car Dealer Code": "63360AA",
        "CV Dealer Code": "63361AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Huddersfield",
        "Address1": "St. Andrews Road",
        "Address2": "Huddersfield",
        "Address3": "",
        "Address4": "",
        "Post Code": "HD1 6RJ",
        "Phone Number": "0343 216 1503",
        "Fax Number": "01484 518 225",
        "CMA Number": "84",
        "CMA Description": "Huddersfield",
        "Group Name": "Ford Retail",
        "eastings": "415107",
        "northings": "417397"
    },
    {
        "Site ID": "1055",
        "Base Code": "64290",
        "Main / Car Dealer Code": "64290AA",
        "CV Dealer Code": "64293AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Barnsley",
        "Address1": "Wakefield Road",
        "Address2": "Barnsley",
        "Address3": "South Yorkshire",
        "Address4": "",
        "Post Code": "S71 1NF",
        "Phone Number": "01226 732732",
        "Fax Number": "01226 732867",
        "CMA Number": "101",
        "CMA Description": "Wakefield",
        "Group Name": "Ford Retail",
        "eastings": "435076",
        "northings": "407745"
    },
    {
        "Site ID": "1397",
        "Base Code": "64290",
        "Main / Car Dealer Code": "97715AA",
        "CV Dealer Code": "97714AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Barnsley BC (FLEET ADMIN)",
        "Location": "Barnsley",
        "Address1": "Wakefield Road",
        "Address2": "Barnsley",
        "Address3": "South Yorskshire",
        "Address4": "",
        "Post Code": "S71 1NF",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "101",
        "CMA Description": "Wakefield",
        "Group Name": "Ford Retail",
        "eastings": "435076",
        "northings": "407745"
    },
    {
        "Site ID": "906",
        "Base Code": "64554",
        "Main / Car Dealer Code": "64554AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Wakefield",
        "Address1": "Calder Island Way",
        "Address2": "Denby Dale Road",
        "Address3": "Wakefield",
        "Address4": "West Yorkshire",
        "Post Code": "WF2 7AW",
        "Phone Number": "01924 290290",
        "Fax Number": "01924 290202",
        "CMA Number": "101",
        "CMA Description": "Wakefield",
        "Group Name": "Ford Retail",
        "eastings": "432787",
        "northings": "418706"
    },
    {
        "Site ID": "1007",
        "Base Code": "64554",
        "Main / Car Dealer Code": "98591AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust First Parts",
        "Location": "Wakefield",
        "Address1": "Ripley Drive",
        "Address2": "Normanton",
        "Address3": "Wakefield",
        "Address4": "West Yorkshire",
        "Post Code": "WF6 1QT",
        "Phone Number": "01924 228500",
        "Fax Number": "01924 224369",
        "CMA Number": "101",
        "CMA Description": "Wakefield",
        "Group Name": "Ford Retail",
        "eastings": "439734",
        "northings": "423209"
    },
    {
        "Site ID": "52",
        "Base Code": "65307",
        "Main / Car Dealer Code": "65307AA",
        "CV Dealer Code": "65777AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Bradford",
        "Address1": "Canal Road",
        "Address2": "Bradford",
        "Address3": "West Yorkshire",
        "Address4": "",
        "Post Code": "BD1 4SR",
        "Phone Number": "01274 756200",
        "Fax Number": "01274 756201",
        "CMA Number": "76",
        "CMA Description": "Bradford",
        "Group Name": "Ford Retail",
        "eastings": "416224",
        "northings": "434777"
    },
    {
        "Site ID": "93",
        "Base Code": "69183",
        "Main / Car Dealer Code": "69183AA",
        "CV Dealer Code": "69184AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Castleford",
        "Address1": "Junction 32 M62",
        "Address2": "Park Road",
        "Address3": "Glasshoughton",
        "Address4": "Castleford, West Yorkshire",
        "Post Code": "WF10 4RJ",
        "Phone Number": "01977 603 644",
        "Fax Number": "01977 603 628",
        "CMA Number": "101",
        "CMA Description": "Wakefield",
        "Group Name": "Ford Retail",
        "eastings": "444082",
        "northings": "424012"
    },
    {
        "Site ID": "152",
        "Base Code": "81125",
        "Main / Car Dealer Code": "81125AA",
        "CV Dealer Code": "81126AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Bristol",
        "Address1": "Winterstoke Road",
        "Address2": "Ashton Gate",
        "Address3": "Bristol",
        "Address4": "",
        "Post Code": "BS3 2LB",
        "Phone Number": "0117 908 9999",
        "Fax Number": "0117 908 9299",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "356876",
        "northings": "171108"
    },
    {
        "Site ID": "1188",
        "Base Code": "81125",
        "Main / Car Dealer Code": "81125BA",
        "CV Dealer Code": "81126BA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Bristol",
        "Address1": "Hayes Way",
        "Address2": "Patchway",
        "Address3": "Bristol",
        "Address4": "",
        "Post Code": "BS34 5BZ",
        "Phone Number": "01173 174150",
        "Fax Number": "01173 174188",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "359629",
        "northings": "180532"
    },
    {
        "Site ID": "321",
        "Base Code": "81125",
        "Main / Car Dealer Code": "81125CA",
        "CV Dealer Code": "81126CA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Weston-Super-Mare",
        "Address1": "Winterstoke Road",
        "Address2": "Weston-Super-Mare",
        "Address3": "Avon",
        "Address4": "",
        "Post Code": "BS23 3YE",
        "Phone Number": "01934 415511",
        "Fax Number": "01934 613003",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "333113",
        "northings": "160673"
    },
    {
        "Site ID": "1162",
        "Base Code": "81125",
        "Main / Car Dealer Code": "81125DA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Bristol",
        "Address1": "Petherbridge Way",
        "Address2": "Muller Road",
        "Address3": "Bristol",
        "Address4": "",
        "Post Code": "BS7 9ND",
        "Phone Number": "01179 510345",
        "Fax Number": "01179 512258",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "360127",
        "northings": "175847"
    },
    {
        "Site ID": "1404",
        "Base Code": "81125",
        "Main / Car Dealer Code": "97701AA",
        "CV Dealer Code": "97702AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Bristol BC (Fleet Admin)",
        "Location": "Bristol",
        "Address1": "150 Winterstoke Road",
        "Address2": "Bristol",
        "Address3": "Somerset",
        "Address4": "",
        "Post Code": "BS3 2LB",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "356876",
        "northings": "171108"
    },
    {
        "Site ID": "1118",
        "Base Code": "81125",
        "Main / Car Dealer Code": "98590AA",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust First Parts",
        "Location": "Bristol",
        "Address1": "183-187 South Liberty Lane",
        "Address2": "Ashton Vale Trading Estate",
        "Address3": "Bristol",
        "Address4": "",
        "Post Code": "BS3 2TN",
        "Phone Number": "01179 536700",
        "Fax Number": "01179 536777",
        "CMA Number": "56",
        "CMA Description": "Bristol",
        "Group Name": "Ford Retail",
        "eastings": "356441",
        "northings": "170111"
    },
    {
        "Site ID": "43",
        "Base Code": "82214",
        "Main / Car Dealer Code": "82214AA",
        "CV Dealer Code": "82213AA",
        "Additional FCSD Dealer Code": "98588AA",
        "Dlr Type": "Main",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Birmingham",
        "Address1": "971 Kingsbury Road",
        "Address2": "Erdington",
        "Address3": "Birmingham",
        "Address4": "",
        "Post Code": "B24 9QB",
        "Phone Number": "0121 377 3000",
        "Fax Number": "0121 377 3049",
        "CMA Number": "40",
        "CMA Description": "Birmingham North",
        "Group Name": "Ford Retail",
        "eastings": "413571",
        "northings": "291146"
    },
    {
        "Site ID": "276",
        "Base Code": "82214",
        "Main / Car Dealer Code": "82214CA",
        "CV Dealer Code": "82213CA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Birmingham",
        "Address1": "Aldridge Road",
        "Address2": "Perry Barr",
        "Address3": "Birmingham",
        "Address4": "West Midlands",
        "Post Code": "B42 2SP",
        "Phone Number": "0121 344 5252",
        "Fax Number": "0121 356 9040",
        "CMA Number": "40",
        "CMA Description": "Birmingham North",
        "Group Name": "Ford Retail",
        "eastings": "407125",
        "northings": "292201"
    },
    {
        "Site ID": "348",
        "Base Code": "82214",
        "Main / Car Dealer Code": "82214DA",
        "CV Dealer Code": "82213DA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Trust Ford",
        "Location": "Tamworth",
        "Address1": "Saxon Drive",
        "Address2": "Tamworth",
        "Address3": "Staffordshire",
        "Address4": "",
        "Post Code": "B79 7HD",
        "Phone Number": "01827 306700",
        "Fax Number": "01827 306715",
        "CMA Number": "40",
        "CMA Description": "Birmingham North",
        "Group Name": "Ford Retail",
        "eastings": "421224",
        "northings": "303922"
    },
    {
        "Site ID": "1405",
        "Base Code": "82214",
        "Main / Car Dealer Code": "97705AA",
        "CV Dealer Code": "97706AA",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "Branch",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "TrustFord Erdington BC (Fleet Admin)",
        "Location": "Erdington",
        "Address1": "971 Kingsbridge Road",
        "Address2": "Erdington",
        "Address3": "West Midlands",
        "Address4": "",
        "Post Code": "B24 9QB",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "40",
        "CMA Description": "Birmingham North",
        "Group Name": "Ford Retail",
        "eastings": "413571",
        "northings": "291146"
    },
    {
        "Site ID": "1274",
        "Base Code": "99301",
        "Main / Car Dealer Code": "99301PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Epsom PartsPlus",
        "Location": "Epsom",
        "Address1": "Unit A2 Longmead Business Centre",
        "Address2": "Blenheim Road",
        "Address3": "Epsom",
        "Address4": "Surrey",
        "Post Code": "KT19 9QQ",
        "Phone Number": "01372 239660",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "520941",
        "northings": "161666"
    },
    {
        "Site ID": "1276",
        "Base Code": "99303",
        "Main / Car Dealer Code": "99303PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Normanton PartsPlus",
        "Location": "Normanton",
        "Address1": "Ripley Drive,",
        "Address2": "Normanton,",
        "Address3": "Wakefield",
        "Address4": "",
        "Post Code": "WF6 1QT",
        "Phone Number": "01924 927170",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "439734",
        "northings": "423209"
    },
    {
        "Site ID": "1277",
        "Base Code": "99304",
        "Main / Car Dealer Code": "99304PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Warrington PartsPlus",
        "Location": "Warrington",
        "Address1": "19 Kingsland Grange",
        "Address2": "Woolston",
        "Address3": "Warrington",
        "Address4": "",
        "Post Code": "WA1 4RW",
        "Phone Number": "01925 591320",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "364530",
        "northings": "390260"
    },
    {
        "Site ID": "1278",
        "Base Code": "99305",
        "Main / Car Dealer Code": "99305PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Thurrock PartsPlus",
        "Location": "Thurrock",
        "Address1": "Unit B, The Triton Centre",
        "Address2": "Weston Avenue",
        "Address3": "Grays,",
        "Address4": "",
        "Post Code": "RM20 3FN",
        "Phone Number": "01708 963300",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "557567",
        "northings": "178193"
    },
    {
        "Site ID": "1279",
        "Base Code": "99306",
        "Main / Car Dealer Code": "99306PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Alperton PartsPlus",
        "Location": "Alperton",
        "Address1": "374 Ealing Road",
        "Address2": "Wembley",
        "Address3": "London",
        "Address4": "",
        "Post Code": "HA0 1HG",
        "Phone Number": "02070 962002",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "518004",
        "northings": "183365"
    },
    {
        "Site ID": "1280",
        "Base Code": "99307",
        "Main / Car Dealer Code": "99307PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Bristol PartsPlus",
        "Location": "Bristol",
        "Address1": "183-187 South Liberty Lane,",
        "Address2": "Ashton Vale Trading Estate,",
        "Address3": "Bristol,",
        "Address4": "",
        "Post Code": "BS3 2TN",
        "Phone Number": "0117 450 7575",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "356441",
        "northings": "170111"
    },
    {
        "Site ID": "1300",
        "Base Code": "99327",
        "Main / Car Dealer Code": "99327PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Hull PartsPlus",
        "Location": "Hull",
        "Address1": "Premier House",
        "Address2": "16 Henry Boot Way",
        "Address3": "",
        "Address4": "",
        "Post Code": "HU4 7DY",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "504897",
        "northings": "426442"
    },
    {
        "Site ID": "1301",
        "Base Code": "99329",
        "Main / Car Dealer Code": "99329PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Lincoln PartsPlus",
        "Location": "Lincoln",
        "Address1": "Units 1-6",
        "Address2": "Avro Court",
        "Address3": "Sadler Road",
        "Address4": "Lincoln",
        "Post Code": "LN6 3RZ",
        "Phone Number": "01522 440532",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "493107",
        "northings": "368298"
    },
    {
        "Site ID": "1314",
        "Base Code": "99349",
        "Main / Car Dealer Code": "99349PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Preston PartsPlus",
        "Location": "Preston",
        "Address1": "Broughton Business Park",
        "Address2": "Fulwood",
        "Address3": "Preston",
        "Address4": "",
        "Post Code": "PR2 9ZA",
        "Phone Number": "01772 282578",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "354463",
        "northings": "433554"
    },
    {
        "Site ID": "1315",
        "Base Code": "99350",
        "Main / Car Dealer Code": "99350PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Tamworth PartsPlus",
        "Location": "Tamworth",
        "Address1": "Unit X&Y, Riverside Industrial Estate",
        "Address2": "Atherstone St",
        "Address3": "Fazeley",
        "Address4": "Tamworth",
        "Post Code": "B78 3RW",
        "Phone Number": "01827 211005",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "420789",
        "northings": "301981"
    },
    {
        "Site ID": "1318",
        "Base Code": "99368",
        "Main / Car Dealer Code": "99368PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Carlisle PartsPlus",
        "Location": "Carlisle",
        "Address1": "Denton Holme Trade Centre",
        "Address2": "Carlisle",
        "Address3": "",
        "Address4": "",
        "Post Code": "CA12 5DF",
        "Phone Number": "01228 588866",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "326624",
        "northings": "523304"
    },
    {
        "Site ID": "1311",
        "Base Code": "99369",
        "Main / Car Dealer Code": "99369PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Glasgow PartsPlus",
        "Location": "Glasgow",
        "Address1": "Unit 1, Rutherglen",
        "Address2": "Glasgow",
        "Address3": "",
        "Address4": "",
        "Post Code": "G73 1BQ",
        "Phone Number": "0141 473 5150",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "261937",
        "northings": "662084"
    },
    {
        "Site ID": "1332",
        "Base Code": "99370",
        "Main / Car Dealer Code": "99370PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Dundee PartsPlus",
        "Location": "Dundee",
        "Address1": "Nobel Road",
        "Address2": "West Gourdie Industrial Estate",
        "Address3": "Dundee",
        "Address4": "",
        "Post Code": "DD2 4UH",
        "Phone Number": "",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "335098",
        "northings": "732071"
    },
    {
        "Site ID": "1319",
        "Base Code": "99371",
        "Main / Car Dealer Code": "99371PP",
        "CV Dealer Code": "",
        "Additional FCSD Dealer Code": "",
        "Dlr Type": "PartsPlus",
        "Operating Company Name": "Ford Retail Limited",
        "Trading Title": "Aberdeen PartsPlus",
        "Location": "Aberdeen",
        "Address1": "Unit 7, Hareness Road,",
        "Address2": "Altens Industrial Estate",
        "Address3": "Aberdeen",
        "Address4": "",
        "Post Code": "AB12 3LE",
        "Phone Number": "01224 608880",
        "Fax Number": "",
        "CMA Number": "900",
        "CMA Description": "PartsPlus",
        "Group Name": "Ford Retail",
        "eastings": "395337",
        "northings": "802726"
    }
]

const getDistance = (a, b) => Math.hypot(a.eastings - b.eastings, a.northings - b.northings)

const byDistance = (a, b) => a.distance - b.distance

const computeDistances = (customer) => {
    return dealers.map(dealer => {
        return {
            ...dealer,
            distance: getDistance(dealer, customer),
        }
    }).sort(byDistance)
}

const nearestDealers = async (customerPostcode) => {
    const location = await getPostcode(customerPostcode)
    return computeDistances(location)
}

export { nearestDealers as default }